#!/bin/bash

# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

set -e
set -o pipefail

SUBMODULE_DIR="third_party/llvm-project"

LLVM_COMMIT="$(git submodule status -- ${SUBMODULE_DIR?} | awk '{print $1}' | tr -d '+')"

sed -i '/Begin autogenerated content/Q' llvm-bazel/llvm-project-overlay/llvm/BUILD
python3 ./llvm-bazel/generate_bazel_build.py \
  --llvm_root=third_party/llvm-project/llvm \
  >> llvm-bazel/llvm-project-overlay/llvm/BUILD

SHORT_COMMIT="$(echo ${LLVM_COMMIT?} | cut -c -12)"

git commit -am "Integrate LLVM at llvm/llvm-project@${SHORT_COMMIT?}"

git tag -f "llvm-project-${LLVM_COMMIT?}"
